#spring:
#   datasource:
#        url: jdbc:mysql://localhost:3306/chat?useUnicode=yes&characterEncoding=UTF-8
#        username: root
#        password: rootpassword
#        driver-class-name: com.mysql.cj.jdbc.Driver
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:chat
    username: admin
    password:

#   thymeleaf:
#     prefix: /WEB-INF/
#     suffix: .html
#     view-names: thymeleaf/*
#

server:
  port: 9090


