#spring:
#   datasource:
#        url: jdbc:mysql://localhost:3306/chat?useUnicode=yes&characterEncoding=UTF-8
#        username: root
#        password: rootpassword
#        driver-class-name: com.mysql.cj.jdbc.Driver
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:chat
    username: admin
    password:
  thymeleaf:
    prefix: classpath:/static/



server:
  port: 9090

management:
  metrics:
    export:
      prometheus:
        enabled: true

    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  endpoints:
    web:
      exposure:
        incule: prometheus



